### ISSUE TITLE
Roadmap to qsctl 2.0

### ISSUE THREAD

**Issue by Xuanwo** [qingstor/qsctl#74]
qsctl's first public commit is <https://github.com/yunify/qsctl/commit/69a52585edb6b14247e8954722d7b6e680769612> at  Jul 5, 2016. It's a long time ago, and everything has been changed. It's time to move forward.

## Reasons

Yep, we still love python, but it's not suitable for qsctl now.

- Python GIL sucks.
- Python 2 will be retired, but our users' still use python 2.7 (even 2.6) https://github.com/yunify/qsctl/issues/73
- qsctl code structure is hard to maintain and harder to add new features.
- It's hard to distribute python version's qsctl in binary.

## Promise

- We will try our best to keep qsctl bug free and do not have known vulnerability.
- We will try our best to keep qsctl stable and do not break any old features.
- We will try our best to make qsctl faster.
- We will add more user-friendly features in qsctl, such as `cat`, `tee`, `initialization wizard`.

## Roadmap

Current Stage: `Beta`

### Alpha Stage

In alpha stage, we will implement all features that qsctl used to support and add features that we promised.

Old features:

- [x] cp (cp -r is not implemented)
- [x] ls
- [x] mb
- [x] rb
- [x] mv
- [x] rm
- [x] sync
- [x] presign

New features:

- [x] stat
- [x] cat
- [x] tee
- [x] initialization wizard
- [ ] qsutil cp support wildcard *, like bash cp https://github.com/yunify/qsctl/issues/28

Fix bug:

- [ ] met error when install qsctl https://github.com/yunify/qsctl/issues/73
- [ ] qsctl cp exit with 0 on error https://github.com/yunify/qsctl/issues/71
- [ ] sys.exit will only exit child thread https://github.com/yunify/qsctl/issues/64
- [ ] qsctl doesn't handle Ctrl+C on windows https://github.com/yunify/qsctl/issues/61

### Beta Stage

In beta stage, we will invite external users to test the qsctl 2.0, and fix every bug we found.

During this stage, we are accepting community's feature request. Some of them will be implemented in beta stage, and others will added in stable stage.

### RC Stage

In RC stage, we will prepare for the stable release: fix bug, refactor, tests ...

### Stable Stage

qsctl 2.0 is ready!

No breaking changes will be introduced until qsctl 3.0

**Comment by Xuanwo** [comment]
v2.0.0-beta.1 released https://github.com/yunify/qsctl/releases/tag/v2.0.0-beta.1
